baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

[author]
  name = "Yanko Ivanov"
  homepage = "https://yanko.dev"
  twitter = "https://twitter.com/yanko__ivanov"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "02.01.2006 15:04"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Djordje Atlialp"
  keywords = "homepage, blog, science, informatics, development, programming"
  homeSubtitle = "Senior web dev. Team Lead. Curious Mind."
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

[languages]
  [languages.en]
    title = "Yanko Ivanov"
    subtitle = "Senior web dev. Team Lead. Curious Mind."
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd ~/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "cv"
        name = "CV"
        url = "https://www.visualcv.com/yanko-ivanov/"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"